posix-process:
	gcc posix-process.c -o ${ELARRARTE}/exec/posix-process

posix-thread:
	gcc posix-thread.c -o ${ELARRARTE}/exec/posix-thread -l pthread 

os:
	gcc os.c -o ${ELARRARTE}/exec/os

os-mt:
	gcc os-mt.c -o ${ELARRARTE}/exec/os-mt -l pthread -lncurses -lpanel

os-process:
	gcc os-process.c -o ${ELARRARTE}/exec/os-process

list-test:
	gcc list-test.c -o ${ELARRARTE}/exec/list-test

window-test:
	gcc window-test.c -o ${ELARRARTE}/exec/window-test -lncurses -lpanel

