posix-process:
	gcc posix-process.c -o ${ELARRARTE}/exec/posix-process

posix-thread:
	gcc posix-thread.c -o ${ELARRARTE}/exec/posix-thread -l pthread 

os-mt:
	gcc os-mt.c -o ${ELARRARTE}/exec/os-mt -l pthread -lncurses -lpanel

os-process:
	gcc os-process.c -o ${ELARRARTE}/exec/os-process

test-socket-server:
	gcc test-socket-server.c -o ${ELARRARTE}/exec/test-socket-server

test-socket-client:
	gcc test-socket-client.c -o ${ELARRARTE}/exec/test-socket-client