posix-process:
	gcc posix-process.c -o ${ELARRARTE}/exec/posix-process

posix-thread:
	gcc posix-thread.c -o ${ELARRARTE}/exec/posix-thread -l pthread 

os-mt:
	gcc os-mt.c -o ${ELARRARTE}/exec/os-mt -l pthread -lncurses -lpanel

os-process:
	gcc os-process.c -o ${ELARRARTE}/exec/os-process

list-test:
	gcc list-test.c -o ${ELARRARTE}/exec/list-test

test:
	gcc test.c -o ${ELARRARTE}/exec/test -lncurses -lpanel

aso-reader-wos:
	gcc aso-reader-wos.c -o ${ELARRARTE}/exec/aso-reader-wos

aso-writer-wos:
	gcc aso-writer-wos.c -o ${ELARRARTE}/exec/aso-writer-wos

aso-reader-ws:
	gcc aso-reader-ws.c -o ${ELARRARTE}/exec/aso-reader-ws

aso-writer-ws:
	gcc aso-writer-ws.c -o ${ELARRARTE}/exec/aso-writer-ws

aso-create-resources:
	gcc aso-create-resources.c -o ${ELARRARTE}/exec/aso-create-resources

aso-remove-resources:
	gcc aso-remove-resources.c -o ${ELARRARTE}/exec/aso-remove-resources

